# Generated by Django 5.2.8 on 2025-11-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Resumen de la receta o notas generales.', verbose_name='Descripción breve')),
                ('instructions', models.TextField(help_text='Texto libre con los pasos de la receta.', verbose_name='Instrucciones')),
                ('ingredients_text', models.TextField(help_text='Lista de ingredientes en texto libre.', verbose_name='Ingredientes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la taxonomía')),
            ],
            options={
                'verbose_name': 'Taxonomía',
                'verbose_name_plural': 'Taxonomías',
            },
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la faceta')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Número para ordenar las facetas en la interfaz.', verbose_name='Orden de visualización')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='recipes.taxonomy')),
            ],
            options={
                'verbose_name': 'Faceta',
                'verbose_name_plural': 'Facetas',
                'ordering': ('order', 'name'),
                'unique_together': {('taxonomy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del término')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='recipes.facet')),
                ('parent', models.ForeignKey(blank=True, help_text='Término padre (opcional) para crear jerarquías.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recipes.term')),
            ],
            options={
                'verbose_name': 'Término',
                'verbose_name_plural': 'Términos',
                'ordering': ('facet', 'parent__id', 'order', 'name'),
                'unique_together': {('facet', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='RecipeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.term')),
            ],
            options={
                'verbose_name': 'Etiqueta de receta',
                'verbose_name_plural': 'Etiquetas de receta',
                'unique_together': {('recipe', 'term')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.RecipeTerm', to='recipes.term'),
        ),
    ]
