# Generated by Django 5.2.8 on 2025-11-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente desde el título.', max_length=250, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
